// Builds public/icons.svg, the Lucide sprite, from ICON_NAMES in src/ui/icons.js.
//   node scripts/build-icons.mjs           # write the sprite
//   node scripts/build-icons.mjs --check   # fail if the committed sprite is stale
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ICON_NAMES } from '../src/ui/icons.js';

const ROOT = resolve(fileURLToPath(new URL('..', import.meta.url)));
const OUT = resolve(ROOT, 'public', 'icons.svg');
const require = createRequire(import.meta.url);
const LUCIDE = dirname(require.resolve('lucide-static/package.json'));
const { version } = JSON.parse(readFileSync(resolve(LUCIDE, 'package.json'), 'utf8'));

function symbol(name) {
  const source = readFileSync(resolve(LUCIDE, 'icons', `${name}.svg`), 'utf8');
  const body = /<svg[^>]*>([\s\S]*?)<\/svg>/.exec(source)?.[1];
  if (!body) throw new Error(`Cannot read lucide-static icon ${name}`);
  const shapes = body
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)
    .join('');
  return `<symbol id="i-${name}" viewBox="0 0 24 24">${shapes}</symbol>`;
}

// Stroke, fill, caps, and joins are inherited from the `.icon` rule so CSS
// controls weight and color; the symbols carry geometry only.
const sprite = `<svg xmlns="http://www.w3.org/2000/svg"><!-- Lucide v${version} (ISC), generated by scripts/build-icons.mjs from src/ui/icons.js -->\n${[...new Set(ICON_NAMES)].sort().map(symbol).join('\n')}\n</svg>\n`;

if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(OUT, 'utf8');
  } catch {
    // missing sprite: reported below
  }
  if (current !== sprite) {
    console.error('public/icons.svg is out of date with ICON_NAMES in src/ui/icons.js; run `npm run icons` and commit it.');
    process.exit(1);
  }
  console.log(`public/icons.svg is current (${ICON_NAMES.length} icons, Lucide v${version}).`);
} else {
  writeFileSync(OUT, sprite);
  console.log(`Wrote public/icons.svg (${ICON_NAMES.length} icons, ${sprite.length} bytes, Lucide v${version}).`);
}
